## Analises e geração dos gráficos

In [77]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

pd.set_option("display.max_columns", None)

In [78]:
cores = ["#1F77B4", "#FFD700"]

In [79]:
app = pd.read_csv('../results/app_metrics_test_512kb.csv')
net = pd.read_csv('../results/network_metrics_512kb.csv')
app.head()

,run,scenario,protocol,file,delay_ms,loss_percent,status,bytes_expected,bytes_received,delivery_rate,elapsed_time_s,throughput_bps,retransmissions,pcap_file,network_csv_file
0,1,A,TCP,test_512kb.bin,10,0,success,524288,524288,1.0,0.0527,9943402.59,NaN,captures/tcp_scenario_a_run_1.pcap,captures/tcp_scenario_a_run_1.csv
1,1,A,RUDP,test_512kb.bin,10,0,success,524288,524288,1.0,1.5590,336293.56,0.0,captures/rudp_scenario_a_run_1.pcap,captures/rudp_scenario_a_run_1.csv
2,1,B,TCP,test_512kb.bin,50,10,success,524288,524288,1.0,1.7639,297228.73,NaN,captures/tcp_scenario_b_run_1.pcap,captures/tcp_scenario_b_run_1.csv
3,1,B,RUDP,test_512kb.bin,50,10,success,524288,524288,1.0,58.1541,9015.49,191.0,captures/rudp_scenario_b_run_1.pcap,captures/rudp_scenario_b_run_1.csv
4,1,C,TCP,test_512kb.bin,100,20,success,524288,524288,1.0,14.8159,35386.92,NaN,captures/tcp_scenario_c_run_1.pcap,captures/tcp_scenario_c_run_1.csv

In [80]:
net.head()

,run,scenario,protocol,pcap_file,network_packet_count,network_total_bytes,network_duration_s,network_throughput_bps
0,1,A,RUDP,captures\rudp_scenario_a_run_1.pcap,1198,719592,4.110436,175064.641934
1,1,A,TCP,captures\tcp_scenario_a_run_1.pcap,164,577386,8.032551,71880.775658
2,1,B,RUDP,captures\rudp_scenario_b_run_1.pcap,1300,742159,58.153333,12762.106011
3,1,B,TCP,captures\tcp_scenario_b_run_1.pcap,407,552104,5.263348,104895.973865
4,1,C,RUDP,captures\rudp_scenario_c_run_1.pcap,1635,928338,152.531194,6086.217355

In [81]:
dados = app.merge(net, on = ['run', 'scenario', 'protocol'], how = 'inner')
dados

,run,scenario,protocol,file,delay_ms,loss_percent,status,bytes_expected,bytes_received,delivery_rate,elapsed_time_s,throughput_bps,retransmissions,pcap_file_x,network_csv_file,pcap_file_y,network_packet_count,network_total_bytes,network_duration_s,network_throughput_bps
0,1,A,TCP,test_512kb.bin,10,0,success,524288,524288,1.0,0.0527,9943402.59,NaN,captures/tcp_scenario_a_run_1.pcap,captures/tcp_scenario_a_run_1.csv,captures\tcp_scenario_a_run_1.pcap,164,577386,8.032551,7.188078e+04
1,1,A,RUDP,test_512kb.bin,10,0,success,524288,524288,1.0,1.5590,336293.56,0.0,captures/rudp_scenario_a_run_1.pcap,captures/rudp_scenario_a_run_1.csv,captures\rudp_scenario_a_run_1.pcap,1198,719592,4.110436,1.750646e+05
2,1,B,TCP,test_512kb.bin,50,10,success,524288,524288,1.0,1.7639,297228.73,NaN,captures/tcp_scenario_b_run_1.pcap,captures/tcp_scenario_b_run_1.csv,captures\tcp_scenario_b_run_1.pcap,407,552104,5.263348,1.048960e+05
3,1,B,RUDP,test_512kb.bin,50,10,success,524288,524288,1.0,58.1541,9015.49,191.0,captures/rudp_scenario_b_run_1.pcap,captures/rudp_scenario_b_run_1.csv,captures\rudp_scenario_b_run_1.pcap,1300,742159,58.153333,1.276211e+04
4,1,C,TCP,test_512kb.bin,100,20,success,524288,524288,1.0,14.8159,35386.92,NaN,captures/tcp_scenario_c_run_1.pcap,captures/tcp_scenario_c_run_1.csv,captures\tcp_scenario_c_run_1.pcap,531,535810,20.375501,2.629678e+04
5,1,C,RUDP,test_512kb.bin,100,20,success,524288,524288,1.0,149.0932,3516.51,480.0,captures/rudp_scenario_c_run_1.pcap,captures/rudp_scenario_c_run_1.csv,captures\rudp_scenario_c_run_1.pcap,1635,928338,152.531194,6.086217e+03
6,2,A,TCP,test_512kb.bin,10,0,success,524288,524288,1.0,0.0653,8032140.11,NaN,captures/tcp_scenario_a_run_2.pcap,captures/tcp_scenario_a_run_2.csv,captures\tcp_scenario_a_run_2.pcap,112,531714,5.233553,1.015971e+05
7,2,A,RUDP,test_512kb.bin,10,0,success,524288,524288,1.0,1.5490,338472.75,0.0,captures/rudp_scenario_a_run_2.pcap,captures/rudp_scenario_a_run_2.csv,captures\rudp_scenario_a_run_2.pcap,1027,590654,1.547940,3.815742e+05
8,2,B,TCP,test_512kb.bin,50,10,success,524288,524288,1.0,0.3641,1440043.83,NaN,captures/tcp_scenario_b_run_2.pcap,captures/tcp_scenario_b_run_2.csv,captures\tcp_scenario_b_run_2.pcap,420,554194,1.473215,3.761800e+05
9,2,B,RUDP,test_512kb.bin,50,10,success,524288,524288,1.0,66.7588,7853.46,222.0,captures/rudp_scenario_b_run_2.pcap,captures/rudp_scenario_b_run_2.csv,captures\rudp_scenario_b_run_2.pcap,1325,758175,66.757643,1.135713e+04
10,2,C,TCP,test_512kb.bin,100,20,success,524288,524288,1.0,17.5020,29955.86,NaN,captures/tcp_scenario_c_run_2.pcap,captures/tcp_scenario_c_run_2.csv,captures\tcp_scenario_c_run_2.pcap,583,564292,21.416636,2.634830e+04
11,2,C,RUDP,test_512kb.bin,100,20,success,524288,524288,1.0,141.1546,3714.28,452.0,captures/rudp_scenario_c_run_2.pcap,captures/rudp_scenario_c_run_2.csv,captures\rudp_scenario_c_run_2.pcap,1600,910833,143.660315,6.340185e+03
12,3,A,TCP,test_512kb.bin,10,0,success,524288,524288,1.0,0.0519,10099493.22,NaN,captures/tcp_scenario_a_run_3.pcap,captures/tcp_scenario_a_run_3.csv,captures\tcp_scenario_a_run_3.pcap,123,532440,5.243427,1.015443e+05
13,3,A,RUDP,test_512kb.bin,10,0,success,524288,524288,1.0,1.5630,335426.91,0.0,captures/rudp_scenario_a_run_3.pcap,captures/rudp_scenario_a_run_3.csv,captures\rudp_scenario_a_run_3.pcap,1027,590654,1.562375,3.780488e+05
14,3,B,TCP,test_512kb.bin,50,10,success,524288,524288,1.0,2.4143,217156.04,NaN,captures/tcp_scenario_b_run_3.pcap,captures/tcp_scenario_b_run_3.csv,captures\tcp_scenario_b_run_3.pcap,467,556036,5.166373,1.076260e+05
15,3,B,RUDP,test_512kb.bin,50,10,success,524288,524288,1.0,62.2267,8425.45,206.0,captures/rudp_scenario_b_run_3.pcap,captures/rudp_scenario_b_run_3.csv,captures\rudp_scenario_b_run_3.pcap,1321,754800,64.868787,1.163580e+04
16,3,C,TCP,test_512kb.bin,100,20,success,524288,524288,1.0,12.3920,42308.47,NaN,captures/tcp_scenario_c_run_3.pcap,captures/tcp_scenario_c_run_3.csv,captures\tcp_scenario_c_run_3.pcap,568,531308,18.251864,2.910979e+04
17,3,C,RUDP,test_512kb.bin,100,20,success,524288,524288,1.0,164.1528,3193.90,528.0,captures/rudp_scenario_c_run_3.pcap,captures/rudp_scenario_c_run_3.csv,captures\rudp_scenario_c_run_3.pcap,1691,959553,171.608639,5.591519e+03
18,4,A,TCP,test_512kb.bin,10,0,success,524288,524288,1.0,0.0653,8032726.92,NaN,captures/tcp_scenario_a_run_4.pcap,captures/tcp_scenario_a_run_4.csv,captures\tcp_scenario_a_run_4.pcap,185,536580,0.113723,4.718305e+06
19,4,A,RUDP,test_512kb.bin,10,0,success,524288,524288,1.0,1.5494,338376.13,0.0,captures/rudp_scenario_a_run_4.pcap,captures/rudp_scenario_a_run_4.csv,captures\rudp_scenario_a_run_4.pcap,1027,590654,1.548505,3.814350e+05
20,4,B,TCP,test_512kb.bin,50,10,success,524288,524288,1.0,6.9823,75088.37,NaN,captures/tcp_scenario_b_run_4.pcap,captures/tcp_scenario_b_run_4.csv,captures\tcp_scenario_b_run_4.pcap,483,557112,7.802712,7.139979e+04
21,4,B,RUDP,test_512kb.bin,50,10,success,524288,524288,1.0,54.8715,9554.84,180.0,captures/rudp_scenario_b_run_4.pcap,captures/rudp_scenario_b_run_4.csv,captures\rudp_scenario_b_run_4.pcap,1283,732893,54.870499,1.335678e+04
22,4,C,TCP,test_512kb.bin,100,20,success,524288,524288,1.0,18.5338,28288.14,NaN,captures/tcp_scenario_c_run_4.pcap,captures/tcp_scenario_c_run_4.csv,captures\tcp_scenario_c_run_4.pcap,576,563514,22.045522,2.556138e+04
23,4,C,RUDP,test_512kb.bin,100,20,success,524288,524288,1.0,178.6487,2934.74,583.0,captures/rudp_scenario_c_run_4.pcap,captures/rudp_scenario_c_run_4.csv,captures\rudp_scenario_c_run_4.pcap,1729,981460,178.647262,5.493843e+03
24,5,A,TCP,test_512kb.bin,10,0,success,524288,524288,1.0,0.0493,10625148.60,NaN,captures/tcp_scenario_a_run_5.pcap,captures/tcp_scenario_a_run_5.csv,captures\tcp_scenario_a_run_5.pcap,108,531450,5.061743,1.049935e+05
25,5,A,RUDP,test_512kb.bin,10,0,success,524288,524288,1.0,1.5561,336919.38,0.0,captures/rudp_scenario_a_run_5.pcap,captures/rudp_scenario_a_run_5.csv,captures\rudp_scenario_a_run_5.pcap,1027,590654,1.555396,3.797451e+05
26,5,B,TCP,test_512kb.bin,50,10,success,524288,524288,1.0,2.8718,182561.91,NaN,captures/tcp_scenario_b_run_5.pcap,captures/tcp_scenario_b_run_5.csv,captures\tcp_scenario_b_run_5.pcap,471,556220,4.346995,1.279551e+05
27,5,B,RUDP,test_512kb.bin,50,10,success,524288,524288,1.0,71.9850,7283.30,241.0,captures/rudp_scenario_b_run_5.pcap,captures/rudp_scenario_b_run_5.csv,captures\rudp_scenario_b_run_5.pcap,1359,776707,71.983455,1.079008e+04
28,5,C,TCP,test_512kb.bin,100,20,success,524288,524288,1.0,22.3761,23430.69,NaN,captures/tcp_scenario_c_run_5.pcap,captures/tcp_scenario_c_run_5.csv,captures\tcp_scenario_c_run_5.pcap,616,566514,28.259643,2.004675e+04
29,5,C,RUDP,test_512kb.bin,100,20,success,524288,524288,1.0,163.9672,3197.52,532.0,captures/rudp_scenario_c_run_5.pcap,captures/rudp_scenario_c_run_5.csv,captures\rudp_scenario_c_run_5.pcap,1713,973305,164.890666,5.902730e+03

In [82]:
dados['overhead_bytes'] = (dados['network_total_bytes'] - dados['bytes_expected'])
dados['overhead_ratio'] = (dados['network_total_bytes'] / dados['bytes_expected'])
dados['throughput_ratio'] = (dados['throughput_bps'] - dados['network_throughput_bps'])

In [83]:
dados.head()

,run,scenario,protocol,file,delay_ms,loss_percent,status,bytes_expected,bytes_received,delivery_rate,elapsed_time_s,throughput_bps,retransmissions,pcap_file_x,network_csv_file,pcap_file_y,network_packet_count,network_total_bytes,network_duration_s,network_throughput_bps,overhead_bytes,overhead_ratio,throughput_ratio
0,1,A,TCP,test_512kb.bin,10,0,success,524288,524288,1.0,0.0527,9943402.59,NaN,captures/tcp_scenario_a_run_1.pcap,captures/tcp_scenario_a_run_1.csv,captures\tcp_scenario_a_run_1.pcap,164,577386,8.032551,71880.775658,53098,1.101276,9.871522e+06
1,1,A,RUDP,test_512kb.bin,10,0,success,524288,524288,1.0,1.5590,336293.56,0.0,captures/rudp_scenario_a_run_1.pcap,captures/rudp_scenario_a_run_1.csv,captures\rudp_scenario_a_run_1.pcap,1198,719592,4.110436,175064.641934,195304,1.372513,1.612289e+05
2,1,B,TCP,test_512kb.bin,50,10,success,524288,524288,1.0,1.7639,297228.73,NaN,captures/tcp_scenario_b_run_1.pcap,captures/tcp_scenario_b_run_1.csv,captures\tcp_scenario_b_run_1.pcap,407,552104,5.263348,104895.973865,27816,1.053055,1.923328e+05
3,1,B,RUDP,test_512kb.bin,50,10,success,524288,524288,1.0,58.1541,9015.49,191.0,captures/rudp_scenario_b_run_1.pcap,captures/rudp_scenario_b_run_1.csv,captures\rudp_scenario_b_run_1.pcap,1300,742159,58.153333,12762.106011,217871,1.415556,-3.746616e+03
4,1,C,TCP,test_512kb.bin,100,20,success,524288,524288,1.0,14.8159,35386.92,NaN,captures/tcp_scenario_c_run_1.pcap,captures/tcp_scenario_c_run_1.csv,captures\tcp_scenario_c_run_1.pcap,531,535810,20.375501,26296.776809,11522,1.021976,9.090143e+03

- Throughput médio

In [84]:
summary = (
    dados.groupby(["scenario", "protocol"])
      .agg(
          mean_throughput=("throughput_bps", "mean"),
          std_throughput=("throughput_bps", "std")
      )
      .reset_index()
)

summary

  scenario protocol  mean_throughput  std_throughput
0        A     RUDP       337097.746    1.322415e+03
1        A      TCP      9346582.288    1.225946e+06
2        B     RUDP         8426.508    9.021284e+02
3        B      TCP       442415.776    5.633685e+05
4        C     RUDP         3311.390    3.053809e+02
5        C      TCP        31874.016    7.229210e+03

In [85]:
summary = (
    dados.groupby(["scenario", "protocol"])
      .agg(
          mean_throughput=("throughput_bps", "mean"),
          std_throughput=("throughput_bps", "std")
      )
      .reset_index()
)

fig = px.bar(
    summary,
    x="scenario",
    y="mean_throughput",
    color="protocol",
    barmode="group",
    error_y="std_throughput",
    title="Throughput médio da aplicação",
    labels={
        "scenario": "Cenário",
        "mean_throughput": "Throughput médio (B/s)",
        "protocol": "Protocolo"
    },
    color_discrete_sequence=cores
)

fig.update_yaxes(type="log")

fig.write_image(
    "../results/figures/throughput_app.png",
)
fig.show()

- Tempo médio de transferência por cenário.

In [86]:
summary_time = (
    dados.groupby(["scenario", "protocol"])
      .agg(
          mean_time=("elapsed_time_s", "mean"),
          std_time=("elapsed_time_s", "std")
      )
      .reset_index()
)

summary_time

  scenario protocol  mean_time   std_time
0        A     RUDP    1.55530   0.006085
1        A      TCP    0.05690   0.007770
2        B     RUDP   62.79922   6.797251
3        B      TCP    2.87928   2.480990
4        C     RUDP  159.40330  14.603814
5        C      TCP   17.12396   3.789265

In [87]:
fig = px.bar(
    summary_time,
    x="scenario",
    y="mean_time",
    color="protocol",
    barmode="group",
    error_y="std_time",
    title="Tempo médio de transferência por cenário",
    labels={
        "scenario": "Cenário",
        "mean_time": "Tempo médio (s)",
        "protocol": "Protocolo"
    },
    color_discrete_sequence=cores
)

fig.write_image(
    "../results/figures/tempo_medio_transferencia.png",
)

fig.show()

- Retransmissões do R-UDP

In [88]:
rudp = dados[dados["protocol"] == "RUDP"]

summary_retrans = (
    rudp.groupby("scenario")
        .agg(
            mean_retransmissions=("retransmissions", "mean"),
            std_retransmissions=("retransmissions", "std")
        )
        .reset_index()
)

summary_retrans

  scenario  mean_retransmissions  std_retransmissions
0        A                   0.0             0.000000
1        B                 208.0            24.300206
2        C                 515.0            50.685304

In [89]:
fig = px.bar(
    summary_retrans,
    x="scenario",
    y="mean_retransmissions",
    error_y="std_retransmissions",
    title="Retransmissões médias do protocolo R-UDP",
    labels={
        "scenario": "Cenário",
        "mean_retransmissions": "Retransmissões médias"
    },
    color_discrete_sequence=cores
)

fig.write_image(
    "../results/figures/retransmissoes_rudp.png",
)

fig.show()

- Overhead de Rede

In [90]:
dados["overhead_bytes"] = (
    dados["network_total_bytes"]
    - dados["bytes_expected"]
)

In [91]:
dados[
    [
        "scenario",
        "protocol",
        "bytes_expected",
        "network_total_bytes",
        "overhead_bytes"
    ]
].head()

  scenario protocol  bytes_expected  network_total_bytes  overhead_bytes
0        A      TCP          524288               577386           53098
1        A     RUDP          524288               719592          195304
2        B      TCP          524288               552104           27816
3        B     RUDP          524288               742159          217871
4        C      TCP          524288               535810           11522

In [92]:
dados[
    [
        "scenario",
        "protocol",
        "bytes_expected",
        "network_total_bytes",
        "overhead_bytes"
    ]
].head()

  scenario protocol  bytes_expected  network_total_bytes  overhead_bytes
0        A      TCP          524288               577386           53098
1        A     RUDP          524288               719592          195304
2        B      TCP          524288               552104           27816
3        B     RUDP          524288               742159          217871
4        C      TCP          524288               535810           11522

In [93]:
summary_overhead = (
    dados.groupby(["scenario", "protocol"])
      .agg(
          mean_overhead=("overhead_bytes", "mean"),
          std_overhead=("overhead_bytes", "std")
      )
      .reset_index()
)

summary_overhead

  scenario protocol  mean_overhead  std_overhead
0        A     RUDP        92153.6  57662.826577
1        A      TCP        17626.0  19937.441611
2        B     RUDP       228658.8  16687.173613
3        B      TCP        30845.2   1998.122919
4        C     RUDP       426409.8  30103.886555
5        C      TCP        27999.6  17205.980437

In [94]:
fig = px.bar(
    summary_overhead,
    x="scenario",
    y="mean_overhead",
    color="protocol",
    barmode="group",
    error_y="std_overhead",
    title="Overhead médio observado na rede",
    labels={
        "scenario": "Cenário",
        "mean_overhead": "Overhead médio (bytes)",
        "protocol": "Protocolo"
    },
    color_discrete_sequence=cores
)

fig.write_image(
    "../results/figures/overhead_rede.png",

)

fig.show()

- Quantidade média de pacotes observados na rede

In [95]:
summary_packets = (
    dados.groupby(["scenario", "protocol"])
      .agg(
          mean_packets=("network_packet_count", "mean"),
          std_packets=("network_packet_count", "std")
      )
      .reset_index()
)

summary_packets

  scenario protocol  mean_packets  std_packets
0        A     RUDP        1061.2    76.473525
1        A      TCP         138.4    34.224260
2        B     RUDP        1317.6    28.667054
3        B      TCP         449.6    33.790531
4        C     RUDP        1673.6    54.385660
5        C      TCP         574.8    30.540138

In [96]:
fig = px.bar(
    summary_packets,
    x="scenario",
    y="mean_packets",
    color="protocol",
    barmode="group",
    error_y="std_packets",
    title="Pacotes médios observados na rede",
    labels={
        "scenario": "Cenário",
        "mean_packets": "Quantidade média de pacotes",
        "protocol": "Protocolo"
    },
    color_discrete_sequence=cores
)

fig.write_image(
    "../results/figures/pacotes_rede.png",

)

fig.show()

- Throughput observado na rede (tcpdump)

In [97]:
summary_network_tp = (
    dados.groupby(["scenario", "protocol"])
      .agg(
          mean_network_tp=("network_throughput_bps", "mean"),
          std_network_tp=("network_throughput_bps", "std")
      )
      .reset_index()
)

summary_network_tp

  scenario protocol  mean_network_tp  std_network_tp
0        A     RUDP     3.391735e+05    9.175090e+04
1        A      TCP     1.019664e+06    2.067647e+06
2        B     RUDP     1.198038e+04    1.052327e+03
3        B      TCP     1.576114e+05    1.238564e+05
4        C     RUDP     5.882899e+03    3.489660e+02
5        C      TCP     2.547260e+04    3.321259e+03

In [98]:
fig = px.bar(
    summary_network_tp,
    x="scenario",
    y="mean_network_tp",
    color="protocol",
    barmode="group",
    error_y="std_network_tp",
    title="Throughput médio observado na rede",
    labels={
        "scenario": "Cenário",
        "mean_network_tp": "Throughput médio da rede (B/s)",
        "protocol": "Protocolo"
    },
    color_discrete_sequence=cores
)

fig.update_yaxes(type="log")

fig.write_image(
    "../results/figures/throughput_rede.png",
)

fig.show()

- Aplicação × Rede

In [99]:
comparison = (
    dados.groupby(["scenario", "protocol"])
      .agg(
          app_tp=("throughput_bps", "mean"),
          net_tp=("network_throughput_bps", "mean")
      )
      .reset_index()
)

comparison

  scenario protocol       app_tp        net_tp
0        A     RUDP   337097.746  3.391735e+05
1        A      TCP  9346582.288  1.019664e+06
2        B     RUDP     8426.508  1.198038e+04
3        B      TCP   442415.776  1.576114e+05
4        C     RUDP     3311.390  5.882899e+03
5        C      TCP    31874.016  2.547260e+04

In [100]:
comparison_long = comparison.melt(
    id_vars=["scenario", "protocol"],
    value_vars=["app_tp", "net_tp"],
    var_name="origem",
    value_name="throughput"
)

comparison_long

   scenario protocol  origem    throughput
0         A     RUDP  app_tp  3.370977e+05
1         A      TCP  app_tp  9.346582e+06
2         B     RUDP  app_tp  8.426508e+03
3         B      TCP  app_tp  4.424158e+05
4         C     RUDP  app_tp  3.311390e+03
5         C      TCP  app_tp  3.187402e+04
6         A     RUDP  net_tp  3.391735e+05
7         A      TCP  net_tp  1.019664e+06
8         B     RUDP  net_tp  1.198038e+04
9         B      TCP  net_tp  1.576114e+05
10        C     RUDP  net_tp  5.882899e+03
11        C      TCP  net_tp  2.547260e+04

In [101]:
fig = px.bar(
    comparison_long,
    x="scenario",
    y="throughput",
    color="origem",
    facet_col="protocol",
    barmode="group",
    title="Throughput da aplicação versus throughput observado na rede",
    labels={
        "scenario": "Cenário",
        "throughput": "Throughput (B/s)",
        "origem": "Origem da métrica"
    },
    color_discrete_sequence=cores
)

fig.update_yaxes(type="log")

fig.write_image(
    "../results/figures/aplicacao_vs_rede.png",
)

fig.show()

In [102]:
final_table = (
    dados.groupby(["scenario", "protocol"])
      .agg(
          throughput_mean=("throughput_bps", "mean"),
          throughput_std=("throughput_bps", "std"),
          time_mean=("elapsed_time_s", "mean"),
          time_std=("elapsed_time_s", "std"),
          retrans_mean=("retransmissions", "mean"),
          retrans_std=("retransmissions", "std")
      )
      .round(2)
)

final_table

                   throughput_mean  throughput_std  time_mean  time_std  \
scenario protocol
A        RUDP            337097.75         1322.41       1.56      0.01
         TCP            9346582.29      1225946.10       0.06      0.01
B        RUDP              8426.51          902.13      62.80      6.80
         TCP             442415.78       563368.53       2.88      2.48
C        RUDP              3311.39          305.38     159.40     14.60
         TCP              31874.02         7229.21      17.12      3.79

                   retrans_mean  retrans_std
scenario protocol
A        RUDP               0.0         0.00
         TCP                NaN          NaN
B        RUDP             208.0        24.30
         TCP                NaN          NaN
C        RUDP             515.0        50.69
         TCP                NaN          NaN

In [103]:
final_table.to_csv(
    "../results/final_summary.csv"
)